# Site settings
title:       presequences
email:       andrew@miller-co.com
author:      Andrew Miller
description: "Description goes here"
baseurl:     ""
url:         "http://presequences.com"

# Google analytics
google_analytics: UA-62182426-2


# Optional features
animated:           false
show_related_posts: false
show_post_footers:  false

# Social icons
show_social_icons: true
github_username: andrewpmiller
twitter_username: andrewpmiller
google_plus_id:
linkedin_username: andrewpmiller
bitcoin_url:
paypal_url:
flattr_button:

# Build settings
markdown:     kramdown
permalink:    pretty
paginate:     3
sass:
compressed: true
